# Generated by Django 3.0.7 on 2024-04-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('contact', models.IntegerField(unique=True)),
                ('email', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(blank=True, max_length=16)),
                ('cpassword', models.CharField(max_length=16)),
            ],
        ),
    ]
